# Generated by Django 6.0 on 2025-12-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_ref', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Идентификатор транзакции')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Рассматриваемый'), ('PACKING', 'Упаковка'), ('SHIPPING', 'Доставка'), ('ARRIVING', 'Прибывающий'), ('SUCCESS', 'Успешно')], default='PENDING', max_length=20, verbose_name='Статус доставки')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Рассматриваемый'), ('PROCESSING', 'Обработка'), ('SUCCESSFUL', 'Успешно'), ('CANCELLED', 'Отмененный'), ('FAILED', 'Провал')], default='PENDING', max_length=20, verbose_name='Статус платежа')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('full_name', models.CharField(max_length=1000, null=True, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.CharField(max_length=1000, null=True, verbose_name='Адрес')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Город')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Страна')),
                ('zipcode', models.CharField(max_length=6, null=True, verbose_name='Почтовый индекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='profiles.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('zipcode', models.CharField(max_length=6, verbose_name='Почтовый индекс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
