# Generated by Django 6.0 on 2025-12-21 10:10

import autoslug.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='business_name', verbose_name='URL')),
                ('inn_identification_number', models.CharField(max_length=50, verbose_name='ИНН')),
                ('website_url', models.URLField(null=True, verbose_name='Сайт')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('business_description', models.TextField(verbose_name='Описание бизнеса')),
                ('business_address', models.CharField(max_length=255, verbose_name='Адрес бизнеса')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bank_bic_number', models.CharField(max_length=9)),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='Банковский счет')),
                ('bank_routing_number', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Проверен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
