# Generated by Django 6.0 on 2025-12-21 10:10

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('price_current', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('in_stock', models.IntegerField(default=5, verbose_name='Количество товара')),
                ('image1', models.ImageField(upload_to='product_images/', verbose_name='Первое изображение')),
                ('image2', models.ImageField(blank=True, upload_to='product_images/', verbose_name='Второе изображение')),
                ('image3', models.ImageField(blank=True, upload_to='product_images/', verbose_name='Третье изображение')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
