# Generated by Django 6.0 on 2026-01-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_user_and_product',
        ),
    ]
